<?php

namespace TableBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TableDefaultColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableDefaultColumnRepository extends EntityRepository
{
}
