<?php

namespace TableBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserColumnRepository extends EntityRepository
{
}
