api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

static:
    resource: "@StaticBundle/Controller/"
    type:     annotation
    prefix:   /

table:
    resource: "@TableBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [%httpProtocol%]

ajax:
    resource: "@AjaxBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [%httpProtocol%]

app:
    resource: @AppBundle/Controller/
    type:     annotation
    schemes:  [%httpProtocol%]

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    schemes:  [%httpProtocol%]

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    schemes:  [%httpProtocol%]

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    schemes:  [%httpProtocol%]

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    schemes:  [%httpProtocol%]