<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyGroupRepository extends EntityRepository
{

	/**
	 * Return list of (enabled (default value) or disabled) CompanyGroups of defined Company
	 *
	 * @param \AppBundle\Entity\Company $company
	 * @param bool|true                 $enabled
	 *
	 * @return array
	 */
	public function findCompanyGroupsOfCompany(Company $company, $enabled = true){

		$em = $this->getEntityManager();

		$qb = $em->createQueryBuilder()
			->from('AppBundle:CompanyGroup', 'cg')
			->where('cg.company = :company')
			->andWhere('cg.enabled IN (:enabled)')
			->setParameter('company', $company)
			->setParameter('enabled', $enabled);

		$query = $qb->getQuery();

		return $query->getResult();

	}

}
