<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use UserBundle\Entity\User;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{

	public function getCompaniesOfUserOfUserCompanyTemporalityStatus(User $user, UserCompanyTemporalityStatus $ucts){

		$qb = new QueryBuilder($this->getEntityManager());
		$qb
			->select('co')
			->from('AppBundle:Company', 'co')
			->join('co.userCompanyRelations', 'ucr')
			->join('ucr.temporalities', 'uct')
			->where('uct.until IS NULL')
			->andWhere('ucr.user = :user')
			->andWhere('uct.status = :ucts');

		$qb
			->setParameter('user', $user)
			->setParameter('ucts', $ucts);

		$query = $qb->getQuery();

		$return = $query->getResult();

		return $return;

	}

}
