<?php

namespace AppBundle\Entity;

use AppBundle\DependencyInjection\ORM\EntityRepositoryTool;
use AppBundle\DependencyInjection\ORM\EntityRepositoryToolInterface;
use Doctrine\ORM\EntityRepository;

/**
 * CostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostRepository extends EntityRepository implements EntityRepositoryToolInterface
{

	private static $SUMARIZATIONS = [
		'priceNonVatPlan',
		'rebillingPriceNonVatPlan',
		'priceNonVatReal',
		'rebillingPriceNonVatReal',
	];

	/**
	 * @return array
	 */
	public function getSumarizations(){

		return self::$SUMARIZATIONS;

	}

	public function findByGroupedBy($criteria, $orderBy, $groupByReference, $groupByColumnName){

		$entityRepositoryTool = new EntityRepositoryTool($this->getEntityManager(), 'AppBundle:'.$this->getClassMetadata()->getTableName(), $this);

		return $entityRepositoryTool->findByGroupedBy($criteria, $orderBy, $groupByReference, $groupByColumnName);

	}


}
