<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeWindowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeWindowRepository extends EntityRepository
{
}
